### ISSUE TITLE
[minor] add project description

### ISSUE THREAD

**Issue by pmocz** [anderslogg/geco#4]
Add project description/website link in the "About" section of https://github.com/anderslogg/geco

**Comment by anderslogg** [comment]
What do you mean by a website link? The website for the project is the GitHub page.

**Comment by pmocz** [comment]
Up to you, you don't need to include a website link or you may link to the docs. Its helpful to add tags for your project as well

**Comment by anderslogg** [comment]
We prefer not to include a website or link (keeping it simple).

Tags are new to me, how are they used?

**Comment by pmocz** [comment]
I still recommend adding a project description for improved discoverability so the github page does not say: "No description, website, or topics provided."

I apologize, I wasn't thinking of git tags, but adding github topics/keywords if that is of interest to you, for increased discoverability

**Comment by anderslogg** [comment]
Aha, now I see what you mean. Added now.
